CREATE TABLE IF NOT EXISTS Songs (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    Title VARCHAR(255) NOT NULL,
    Artist VARCHAR(255),
    SourceUrl TEXT NOT NULL,
    CoverImage TEXT,
    DurationSeconds INTEGER NOT NULL DEFAULT 0,
    AddedByUserId UUID REFERENCES Users(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Folders (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    Name VARCHAR(100) NOT NULL,
    UserId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Playlists (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    Name VARCHAR(200) NOT NULL,
    UserId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    FolderId UUID REFERENCES Folders(Id) ON DELETE
    SET NULL,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS PlaylistSongs (
    PlaylistId UUID NOT NULL REFERENCES Playlists(Id) ON DELETE CASCADE,
    SongId UUID NOT NULL REFERENCES Songs(Id) ON DELETE CASCADE,
    SortOrder INTEGER NOT NULL DEFAULT 0,
    AddedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PlaylistId, SongId)
);
CREATE TABLE IF NOT EXISTS ListeningHistory (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    UserId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    SongId UUID NOT NULL REFERENCES Songs(Id) ON DELETE CASCADE,
    ListenDurationSeconds INTEGER NOT NULL,
    ListenedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS UserActivity (
    UserId UUID PRIMARY KEY REFERENCES Users(Id) ON DELETE CASCADE,
    DailyGoalMinutes INTEGER DEFAULT 120,
    CurrentStreakDays INTEGER DEFAULT 0,
    LastActiveDate DATE
);